services:
  db:
    image: postgres:16
    container_name: arin-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arin
    ports:
      - "5432:5432"
    volumes:
      - arin_db_data:/var/lib/postgresql/data

volumes:
  arin_db_data:
